from enum import StrEnum


class RiskLevel(StrEnum):
    LOW = "RISK_LEVEL_LOW"
    MODERATE = "RISK_LEVEL_MODERATE"
    HIGH = "RISK_LEVEL_HIGH"
    UNSPECIFIED = "RISK_LEVEL_UNSPECIFIED"


class CouponType(StrEnum):
    UNSPECIFIED = "COUPON_TYPE_UNSPECIFIED"
    CONSTANT = "COUPON_TYPE_CONSTANT"
    FLOATING = "COUPON_TYPE_FLOATING"
    DISCOUNT = "COUPON_TYPE_DISCOUNT"
    MORTGAGE = "COUPON_TYPE_MORTGAGE"
    FIX = "COUPON_TYPE_FIX"
    VARIABLE = "COUPON_TYPE_VARIABLE"
    OTHER = "COUPON_TYPE_OTHER"
